version: "3"

services:
  app:
    build: .
    command:
      [
        "sh",
        "-c",
        "pip install debugpy && python -m debugpy --wait-for-client --listen 0.0.0.0:8000 -m uvicorn main:app --host 0.0.0.0 --port 8000",
      ]
    volumes:
      - ./app/:/app/app
    ports:
      - 8000:8000
      - 5678:5678

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "StrongPassword!123"
      ACCEPT_EULA: "Y"
      DOCKER_ENV: "true"
    ports:
      - "1433:1433"
    volumes:
      - ./docker_setup.sql:/docker-entrypoint-initdb.d/docker_setup.sql

volumes:
  app:
